### ISSUE TITLE
Uncaught error (sync nor async) if main field is not a string

### ISSUE THREAD

**Issue by unlight** [browserify/resolve#178]
How to repeat:
```
git clone https://gist.github.com/14c93c133d9657411e95959e22e32570.git main-is-not-a-string
cd main-is-not-a-string
npm i
node resolve-material-design-iconic-font.js
```
```js
const resolve = require('resolve');

try {
	resolve('material-design-iconic-font', (err) => {
		console.log('async err', err);
	});	
} catch (err) {
	console.log('sync err', err);
} 
```

Actual:
```
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:168:7)
    at \Dev\browserify-resolve-zavoloklom-material-design-iconic-font-issue-111\node_modules\resolve\lib\async.js:164:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```
Expected:
Error should be caught in callback or in catch

```
resolve: 1.8.1
node v10.8.0
```
Related issues:
https://github.com/unlight/sublime-import-helper/issues/61
https://github.com/zavoloklom/material-design-iconic-font/issues/111

**Comment by unlight** [comment]
main for this package is:
```
  "main": [
    "./dist/css/*",
    "./dist/fonts/*"
  ],
```

**Comment by ljharb** [comment]
@unlight either way, that package is broken; main can only be a string. I’d file a bug on that package.

**Comment by unlight** [comment]
The question is how can I detect that package is broken.

**Comment by ljharb** [comment]
For sure, I definitely think this is a bug :-)

**Comment by ljharb** [comment]
Thanks for the perfect repro - a fix will be merged shortly, and included in the next release.
