### ISSUE TITLE
Resolve 1.13.0 fails to find bootstrap's package.json

### ISSUE THREAD

**Issue by orthur** [browserify/resolve#204]
We have faced issues with new version of resolve.

```
ERROR in ./node_modules/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./node_modules/bootstrap-loader/no-op.js
Module build failed: Error: Cannot find module '/builds/node_modules/bootstrap/package.json/package.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at exports.default (/builds/node_modules/bootstrap-loader/lib/utils/checkBootstrapVersion.js:8:20)
    at Object.module.exports.pitch (/builds/node_modules/bootstrap-loader/lib/bootstrap.loader.js:159:65)
 @ ./node_modules/bootstrap-loader/extractStyles.js 2:0-58
 @ multi whatwg-fetch babel-polyfill ./app.js bootstrap-loader/extractStyles
```
Note `node_modules/bootstrap/package.json/package.json` instead of `node_modules/bootstrap/package.json`
same error as in #157

**Comment by ljharb** [comment]
oops, looks like i repeated the same mistake again. I'll revert and release a v1.13.0 shortly.

**Comment by ljharb** [comment]
v1.13.1 and v1.12.3 are released with this fix. Sorry for the inconvenience!
