### ISSUE TITLE
cannot resolve paths with extentions .min.js

### ISSUE THREAD

**Issue by mishoo78** [browserify/resolve#90]
I believe it should be able to find paths that end with .min.js

**Comment by reggi** [comment]
You can currently do this by adding `.min.js` to extensions, this is not native `require.resolve` functionality.

```
➜  touch example.min.js
➜  node
> require.resolve('./example.min')
'/Users/treggi/Desktop/jest-example/example.min.js'
> require.resolve('./example')
Error: Cannot find module './example'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.resolve (internal/module.js:18:19)
```
